compatibility_date = "2026-07-26"
name = "decap-oauth"
main = "worker.js"
workers_dev = true

routes = [
  "hn.liuxiyu.cn/*"
]

[[d1_databases]]
binding = "DB"
database_name = "csel-users"
database_id = "91a45a26-074e-4f2e-854b-296662c3dd7d"
